language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

before_install:
  - gem install bundler -v '< 2'

cache: bundler

script: bundle exec rake

notifications:
  email: false

sudo: false

git:
  depth: 10

matrix:
  allow_failures:
    - rvm: ruby-head
