language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

cache: bundler

script: bundle exec rake

notifications:
  email: false

sudo: false

git:
  depth: 10

matrix:
  allow_failures:
    - rvm: ruby-head
